name: fetch docs

on:
  push:
    paths:
      - "config/docs.list"
  
  workflow_dispatch:

jobs:
  fetch:

    runs-on: ubuntu-latest
    
    permissions:
      contents: wrtie

    steps:

    - uses: actions/checkout@v4

    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y zstd

    - name: run pipeline
      run: |
        make fetch
        make compress
        make cleanup

    - name: commit artifacts
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add compressed/

        git commit -m "update(compressed): update documents."

        git push
